import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const migration = read('supabase/migrations/20261001112438_own_planner_archived_editions.sql');
const regression = read('tests/own-planner-archived-editions.sql');
assert.match(migration, /public\.get_own_planner_archived_editions\(p_edition_ids uuid\[\]\)/);
assert.match(migration, /stable security definer set search_path=pg_catalog/);
assert.match(migration, /auth\.uid\(\)\) is null[\s\S]*42501/);
assert.match(migration, /cardinality\(p_edition_ids\),0\)>500[\s\S]*22023/);
assert.match(migration, /cardinality\(p_edition_ids\),0\)=0 then return/);
assert.match(migration, /select distinct[\s\S]*join public\.event_editions d on d\.id=own_entry\.edition_id/);
assert.match(migration, /own_entry\.user_id=\(select auth\.uid\(\)\) and d\.id=any\(p_edition_ids\)/);
assert.match(migration, /d\.publication_status='archived' and d\.published_at is not null/);
assert.match(migration, /e\.status='approved' and e\.publication_status='published'/);
assert.match(migration, /'owned_archived'::text/);
assert.match(migration, /revoke all on function public\.get_own_planner_archived_editions\(uuid\[\]\) from public,anon,authenticated/);
assert.match(migration, /grant execute on function public\.get_own_planner_archived_editions\(uuid\[\]\) to authenticated/);
assert.doesNotMatch(migration, /alter table|create policy|alter policy|create (?:or replace )?view|insert into|update public\.|delete from|set row_security/i);
assert.doesNotMatch(migration, /event_sources|event_audit_log|source_review_tasks|event_change_proposals|planner_details|user_id\s+uuid/);
const columns = migration.match(/returns table\(([\s\S]*?)\)\s*language/)?.[1];
assert.ok(columns);
const names = [...columns.matchAll(/(?:^|,)\s*([a-z_]+)\s/g)].map(match => match[1]);
assert.equal(new Set(names).size, names.length);
assert.equal(names.length, 26);
assert.ok(!names.some(name => /notes|crawl|review|audit|user|confidence|verification/.test(name)));
assert.match(regression, /is distinct from 'isolated'/);
assert.match(regression, /own archived edition resolves concrete saved facts/);
assert.match(regression, /foreign Planner binding is not authorization/);
assert.match(regression, /draft and never-published archive remain hidden/);
assert.match(regression, /archived brand remains hidden/);
assert.match(regression, /500/);
assert.match(regression, /rollback;\s*$/);
console.log('Own Planner archive RPC static contract passed: exact own UUID binding, former publication proof, approved brand, 500-ID bound, 26 public core fields and no global access change. SQL/RLS execution is separate.');
