-- Reconstruct the original events table that predates the versioned migration
-- chain. Later migrations deliberately evolve this historical shape into the
-- current production schema.

begin;

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  created_at timestamptz default timezone('utc'::text, now()),
  event_name text,
  sport text,
  date text,
  city text,
  country text,
  address text,
  latitude text,
  longitude text,
  distance text,
  description text,
  event_url text,
  status text,
  created_by uuid,
  data_source text,
  image text
);

comment on table public.events is
  'Historical baseline required before the closed-beta security migrations.';

commit;
